export { App } from "./App";
export { Homepage } from "./Homepage";
export { SignIn } from "./SignIn";
export { SignUp } from "./SignUp";
export { Dashboard } from "./Dashboard";
export { Journal } from "./Journal/Journal";
export { AddActivity } from "./AddActivity/AddActivity";
export { Blog } from "./layout/Footer/Product"
export { Pricing } from "./layout/Footer/Product"
export { About } from "./layout/Footer/Company"
export { Contacts } from "./layout/Footer/Company"
export { Privacy } from "./layout/Footer/Legal"
export { Settings } from "./Settings"
export { Explore } from "./Explore"
